version: "3"

services:
  mysql:
    image: "mysql:latest"
    container_name: "pyhoot-mysql"
    platform: "linux/amd64"
    ports:
      - "3306:3306"
    cap_add:
      - "SYS_NICE"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
